on:
  push:
    branches:
      - main
      - "feature/**"
      - "!feature/exclude-branch"
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
